In [1]:
import numpy as np

In [149]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],
                [2,3,4]])
arr3 = np.array([[1,2,3]])
arr4 = np.array([[[1,2,3],[3,4,5],[4,5,6]], [[2,3,4],[4,5,6],[7,5,4]]])

In [150]:
print('arr1 type : ', type(arr1))
print('arr2 type : ', type(arr2))
print('arr3 type : ', type(arr3))
print('arr4 type : ', type(arr4))

arr1 type :  <class 'numpy.ndarray'>
arr2 type :  <class 'numpy.ndarray'>
arr3 type :  <class 'numpy.ndarray'>
arr4 type :  <class 'numpy.ndarray'>


In [151]:
print('arr1 array 형태 : ', arr1.shape)
print('arr2 array 형태 : ', arr2.shape)
print('arr3 array 형태 : ', arr3.shape)
print('arr4 array 형태 : ', arr4.shape)

arr1 array 형태 :  (3,)
arr2 array 형태 :  (2, 3)
arr3 array 형태 :  (1, 3)
arr4 array 형태 :  (2, 3, 3)


In [152]:
arr4.ndim

3

In [153]:
print('arr1:{:0}차원, arr2:{:1}차원, arr3:{:2}차원, arr4:{:4}차원'.format(arr1.ndim,arr2.ndim,arr3.ndim,arr4.ndim))

arr1:1차원, arr2:2차원, arr3: 2차원, arr4:   3차원


In [39]:
list1 = [1,2,3]
print(type(list1))

<class 'list'>


In [40]:
arr1 = np.array(list1)
print(type(arr1))

<class 'numpy.ndarray'>


In [41]:
print(arr1, arr1.dtype)

[1 2 3] int32


In [43]:
list2 = [1,2,'test']
arr2 = np.array(list2)
print(arr2, arr2.dtype)

['1' '2' 'test'] <U11


In [44]:
list3 = [1,2,3.0]
arr3 = np.array(list3)
print(arr3, type(arr3), arr3.dtype)

[1. 2. 3.] <class 'numpy.ndarray'> float64


In [45]:
arr_int = np.array([1,2,3])
arr_float = arr_int.astype('float64')
print(arr_float, arr_float.dtype)

[1. 2. 3.] float64


In [46]:
arr_int1 = arr_float.astype('int32')
print(arr_int1, arr_int1.dtype)

[1 2 3] int32


In [47]:
arr_float1 = np.array([1.1,2.2,3.3])
arr_int2 = arr_float1.astype('int32')
print(arr_int2, arr_int2.dtype)

[1 2 3] int32


In [134]:
seq_arr = np.arange(10, dtype='float64')
print(seq_arr)
print(seq_arr.dtype, seq_arr.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64 (10,)


In [54]:
seq_arr = np.arange(10).reshape(1, -1)
print(seq_arr)
print(seq_arr.dtype, seq_arr.shape)

[[0 1 2 3 4 5 6 7 8 9]]
int32 (1, 10)


In [55]:
seq_arr = np.arange(1, 10) #default 값 : stop, 추가 인자 : start
print(seq_arr)
print(seq_arr.dtype, seq_arr.shape)

[1 2 3 4 5 6 7 8 9]
int32 (9,)


In [156]:
zero_arr = np.zeros((3, 2))
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64 (3, 2)


In [155]:
zero_arr = np.zeros((3, 2))
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64 (3, 2)


In [158]:
one_arr = np.ones((3, 2), dtype='int32')
print(one_arr)
print(one_arr.dtype, one_arr.shape)

[[1 1]
 [1 1]
 [1 1]]
int32 (3, 2)


In [159]:
arr1 = np.arange(10)
print("arr1 : \n", arr1)
arr2 = arr1.reshape(2,5)
print("arr2 : \n", arr2)
arr3 = arr1.reshape(5, 2)
print("arr3 : \n", arr3)

arr1 : 
 [0 1 2 3 4 5 6 7 8 9]
arr2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [160]:
arr4 = arr1.reshape(-1,5)
print("arr4 : \n", arr4)

arr4 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [164]:
arr1 = np.arange(8)
arr3d = arr1.reshape((2,2,2))
print("arr3d : \n", arr3d.tolist())
print("type : " , type(arr3d.tolist()))
print("arr3d shape ", arr3d.shape)

arr3d : 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
type :  <class 'list'>
arr3d shape  (2, 2, 2)


In [72]:
arr5 = arr3d.reshape(-1, 1)
print("arr5 : \n", arr5.tolist())
print("arr5 shape : ", arr5.shape)

arr5 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
arr5 shape :  (8, 1)


In [78]:
arr1 = np.arange(1, 10)
print(arr1.tolist())
print(arr1[-1])

[1, 2, 3, 4, 5, 6, 7, 8, 9]
9


In [136]:
arr1d = np.arange(1, 10)
arr2d = arr1d.reshape(-1, 3)
print('arr2d : \n', arr2d)

print('arr2d[0:2, 0:2] \n', arr2d[0:2, 0:2])
print('arr2d[1:3, 0:3] \n', arr2d[1:3, 0:3])
print('arr2d[1:3, :] \n', arr2d[1:3, :])
print('arr2d[:, :] \n', arr2d[:, :])
print('arr2d[:2, 1:] \n', arr2d[:2, 1:])
print('arr2d[:2, 0] \n', arr2d[:2, 0])

arr2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
arr2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
arr2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
arr2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[:2, 1:] 
 [[2 3]
 [5 6]]
arr2d[:2, 0] 
 [1 4]


In [140]:
arr1d = np.arange(1, 10)
arr2d = arr1d.reshape(-1, 3)

arr3 = arr2d[[0,1], 2]
print(arr3.tolist())

arr4 = arr2d[[0, 1],0:2]
print(arr4.tolist())

arr5 = arr2d[[0, 1]]
print(arr5)

arr6 = arr1d[[0, 1]]
print(arr6)

[3, 6]
[[1, 2], [4, 5]]
[[1 2 3]
 [4 5 6]]
[1 2]


In [100]:
arr3 = arr1d[arr1d > 5]
arr3

array([6, 7, 8, 9])

In [96]:
arr1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [141]:
index = np.array([5,6,7,8])
print(index)
arr4 = arr1d[index]
arr4

[5 6 7 8]


array([6, 7, 8, 9])

In [165]:
org_arr = np.array([3,1,9,5])
print("원본 : ", org_arr)
sort_arr1 = np.sort(org_arr)
print('sort1 : ', sort_arr1)
print("원본 : ", org_arr)

원본 :  [3 1 9 5]
sort1 :  [1 3 5 9]
원본 :  [3 1 9 5]


In [111]:
np.sort(org_arr)


array([1, 3, 5, 9])

In [112]:
org_arr

array([3, 1, 9, 5])

In [167]:
sort_arr2 = org_arr.sort()
print('arr2 : ', sort_arr2)
print('오리지날 : ', org_arr)

arr2 :  None
오리지날 :  [1 3 5 9]


In [114]:
np.sort(org_arr)

array([1, 3, 5, 9])

In [115]:
org_arr.sort()

In [168]:

desc_arr1 = np.sort(org_arr)[::-1]
desc_arr1


array([9, 5, 3, 1])

In [122]:
desc_arr1

array([9, 5, 3, 1])

In [143]:
arr2d = np.array([[8, 12],
                 [7, 1]])
sort_arr2_axis0 = np.sort(arr2d, axis = 0)
print(sort_arr2_axis0)

[[ 7  1]
 [ 8 12]]


In [169]:
arr2d = np.array([[12, 8],
                 [7, 1]])
sort_arr2_axis2 = np.sort(arr2d, axis= 1)
print(sort_arr2_axis2)

[[ 8 12]
 [ 1  7]]


In [128]:
org_arr = np.array([3, 1, 9, 5])
sort_ind = np.argsort(org_arr)
print(type(sort_ind))
print(sort_ind)

<class 'numpy.ndarray'>
[1 0 3 2]


In [129]:
name_arr = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_arr = np.array([78,95,84,98,88])

score_ind = np.argsort(score_arr)

In [130]:
score_ind

array([0, 2, 4, 1, 3], dtype=int32)

In [132]:
print(name_arr[score_ind])

['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [133]:
name_arr[[0, 2, 4, 1, 3]]

array(['John', 'Sarah', 'Samuel', 'Mike', 'Kate'], dtype='<U6')