In [1]:
import pandas as pd
import numpy as np

In [2]:
titanic_df = pd.read_csv("titanic/train.csv")

In [3]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
print('titanic 변수 type', type(titanic_df))

titanic 변수 type <class 'pandas.core.frame.DataFrame'>


In [5]:
print('DataFrame 크기 : ', titanic_df.shape)

DataFrame 크기 :  (891, 12)


In [6]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 66.2+ KB


In [7]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [8]:
titanic_df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [9]:
titanic_df['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [10]:
type(titanic_df)

pandas.core.frame.DataFrame

In [11]:
type(titanic_df['Pclass'])

pandas.core.series.Series

In [12]:
titanic_df['Pclass'].head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [13]:
type(titanic_df['Pclass'].value_counts())

pandas.core.series.Series

In [14]:
titanic_df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [15]:
np.array([1]).dtype

dtype('int32')

In [16]:
col_name1=['col1']
list1=[1,2,3]
arr1=np.array(list1)
print('arr1 shape : ', arr1.shape)

arr1 shape :  (3,)


In [17]:
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)

1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [18]:
df_arr1 = pd.DataFrame(arr1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_arr1)

1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [19]:
df_list1 = pd.DataFrame(list1, columns=col_name1)
print(df_list1)

   col1
0     1
1     2
2     3


In [20]:
col_name2 = ['col1', 'col2', 'col3']
list2 = [[1,2,3],
        [11,12,13]]
arr2 = np.array(list2)
print('arr2 shape : ', arr2.shape)
df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
df_arr2 = pd.DataFrame(arr2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_arr2)

arr2 shape :  (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [21]:
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict1 = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict1)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


In [22]:
arr3 = df_dict1.values

In [23]:
print('df_dict.value 타입 : ', type(arr3), 'df_dict.values shape : ', arr3.shape)
print(arr3)

df_dict.value 타입 :  <class 'numpy.ndarray'> df_dict.values shape :  (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [24]:
arr4 = titanic_df.values
print(arr4.shape)

(891, 12)


In [25]:
arr4

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [26]:
arr5 = titanic_df.Sex.values
arr5

array(['male', 'female', 'female', 'female', 'male', 'male', 'male',
       'male', 'female', 'female', 'female', 'female', 'male', 'male',
       'female', 'female', 'male', 'male', 'female', 'female', 'male',
       'male', 'female', 'male', 'female', 'female', 'male', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'male', 'male', 'male', 'female', 'female', 'female', 'female',
       'male', 'female', 'female', 'male', 'male', 'female', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'female', 'male', 'female', 'male', 'male', 'female', 'male',
       'male', 'male', 'male', 'female', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'female', 'male', 'female', 'female',
       'male', 'male', 'female', 'male', 'male', 'male', 'male', 'male',
       'male', 'male', 'male', 'male', 'female', 'male', 'female', 'male',
      

In [27]:
list3 = df_dict1.values.tolist()
print('df_dict.values.tolist() 타입 : ', type(list3))
print(list3)

df_dict.values.tolist() 타입 :  <class 'list'>
[[1, 2, 3], [11, 22, 33]]


In [28]:
dict3 = df_dict1.to_dict('list')
print('\n df_dict.to_dict() 타입 : ', type(dict3))
print(dict3)


 df_dict.to_dict() 타입 :  <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [29]:
titanic_df.Pclass.values.tolist()

[3,
 1,
 3,
 1,
 3,
 3,
 1,
 3,
 3,
 2,
 3,
 1,
 3,
 3,
 3,
 2,
 3,
 2,
 3,
 3,
 2,
 2,
 3,
 1,
 3,
 3,
 3,
 1,
 3,
 3,
 1,
 1,
 3,
 2,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 2,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 2,
 1,
 1,
 2,
 3,
 2,
 3,
 3,
 1,
 1,
 3,
 1,
 3,
 2,
 3,
 3,
 3,
 2,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 1,
 2,
 3,
 3,
 3,
 1,
 3,
 3,
 3,
 1,
 3,
 3,
 3,
 1,
 1,
 2,
 2,
 3,
 3,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 1,
 3,
 2,
 3,
 2,
 2,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 3,
 1,
 3,
 3,
 3,
 3,
 2,
 2,
 3,
 3,
 2,
 2,
 2,
 1,
 3,
 3,
 3,
 1,
 3,
 3,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 1,
 3,
 1,
 3,
 1,
 3,
 3,
 3,
 1,
 3,
 3,
 1,
 2,
 3,
 3,
 2,
 3,
 2,
 3,
 1,
 3,
 1,
 3,
 3,
 2,
 2,
 3,
 2,
 1,
 1,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 3,
 2,
 3,
 2,
 3,
 1,
 3,
 2,
 1,
 2,
 3,
 2,
 3,
 3,
 1,
 3,
 2,
 3,
 2,
 3,
 1,
 3,
 2,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 3,
 3,
 2,
 3,
 3,
 1,
 3,
 2,
 1,
 2,


In [30]:
titanic_df.to_dict('list')

{'PassengerId': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
 

In [31]:
titanic_df['Age_10'] = titanic_df['Age'] * 10

In [32]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_10  
0        0         A/5 21171   7.2500   NaN        S   220.0  
1        0          PC 17599  71.2833   C85        C   380.0  
2        0  STON/O2. 3101282   7.9250   NaN        S   260.0  
3        0            113803  53.1000  C123        S   350.0  
4        0            373450   8.0500   NaN        S   350.0  
..     ...               ...      ...   ...      ...     ...  
886      0            211536  13.0000   NaN        S   270.0  
887      0            112053  30.0000   B42        S   190.0  
888      2        W./C. 6607  23.4500   NaN        S     NaN  
889      0            111369  30.0000  C148        C   260.0  
890      0            370376   7.7500   NaN        Q   320.0  

[891 rows x 13 columns]

In [33]:
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1

In [34]:
titanic_drop_df = titanic_df.drop('Age_10', axis=1)

In [35]:
drop_res = titanic_df.drop(['Age_10', 'Family_No'], axis=1, inplace=True)
print('drop_res 결과값 : ', drop_res)
titanic_df.head()

drop_res 결과값 :  None


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [36]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 30)
print('### before axis 0 drop ###')
print(titanic_df.head(3))
print('### after axis 0 drop ###')
print(titanic_df.head(3))

### before axis 0 drop ###
   PassengerId  Survived  Pclass                           Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0            1         0       3        Braund, Mr. Owen Harris    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley...  female  38.0      1      0          PC 17599  71.2833   C85        C
2            3         1       3         Heikkinen, Miss. Laina  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
### after axis 0 drop ###
   PassengerId  Survived  Pclass                           Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0            1         0       3        Braund, Mr. Owen Harris    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley...  female  38.0      1      0          PC 17599  71.2833   C85        C
2        

In [37]:
titanic_df.index

RangeIndex(start=0, stop=891, step=1)

In [38]:
titanic_df.Sex.value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [39]:
titanic_df = pd.read_csv("titanic/train.csv")

In [40]:
titanic_df

PassengerId  Survived  Pclass                           Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0              1         0       3        Braund, Mr. Owen Harris    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1              2         1       1  Cumings, Mrs. John Bradley...  female  38.0      1      0          PC 17599  71.2833   C85        C
2              3         1       3         Heikkinen, Miss. Laina  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3              4         1       1  Futrelle, Mrs. Jacques Hea...  female  35.0      1      0            113803  53.1000  C123        S
4              5         0       3       Allen, Mr. William Henry    male  35.0      0      0            373450   8.0500   NaN        S
..           ...       ...     ...                            ...     ...   ...    ...    ...               ...      ...   ...      ...
886          887         0       2          Montvila, Rev. Juozas    male  27.0      0      0            211536  13.0000   NaN        S
887          888         1       1   Graham, Miss. Margaret Edith  female  19.0      0      0            112053  30.0000   B42        S
888          889         0       3  Johnston, Miss. Catherine ...  female   NaN      1      2        W./C. 6607  23.4500   NaN        S
889          890         1       1          Behr, Mr. Karl Howell    male  26.0      0      0            111369  30.0000  C148        C
890          891         0       3            Dooley, Mr. Patrick    male  32.0      0      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [41]:
indexes = titanic_df.index
print(indexes)
print(type(indexes))
print(type(indexes.tolist()))
print(type(indexes.values))
print(indexes.values)

RangeIndex(start=0, stop=891, step=1)
<class 'pandas.core.indexes.range.RangeIndex'>
<class 'list'>
<class 'numpy.ndarray'>
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215


In [42]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [43]:
series_fair = titanic_df['Fare']
print('Fair Series max 값 : ', series_fair.max())
print('Fair Series sum 값 : ', series_fair.sum())
print('sum() Fair Series 값 : ', sum(series_fair))
print('Fair Series + 3:\n', (series_fair + 3).head())

Fair Series max 값 :  512.3292
Fair Series sum 값 :  28693.9493
sum() Fair Series 값 :  28693.949299999967
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
3    56.1000
4    11.0500
Name: Fare, dtype: float64


In [44]:
series_fair.head()

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

In [45]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass                           Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0      0            1         0       3        Braund, Mr. Owen Harris    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mrs. John Bradley...  female  38.0      1      0          PC 17599  71.2833   C85        C
2      2            3         1       3         Heikkinen, Miss. Laina  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S

In [46]:
print("### before reset_index ###")
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입 : ', type(value_counts))
new_value_counts = value_counts.reset_index(inplace=False, drop=True)
print("### after reset_index ###")
print(new_value_counts)
print('new_value_counts 객체 변수 타입 : ', type(new_value_counts))

### before reset_index ###
3    491
1    216
2    184
Name: Pclass, dtype: int64
value_counts 객체 변수 타입 :  <class 'pandas.core.series.Series'>
### after reset_index ###
0    491
1    216
2    184
Name: Pclass, dtype: int64
new_value_counts 객체 변수 타입 :  <class 'pandas.core.series.Series'>


In [47]:
print('단일 칼럼 데이터 추출:\n', titanic_df['Pclass'].head(3))
print('\n여러 칼럼의 데이터 추출:\n', titanic_df[['Survived', 'Pclass']].head(3))
print('[]안에 ndex는 KeyError오류:\n', titanic_df[0])

단일 칼럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3


KeyError: 0

In [ ]:
print('[]안에 index 슬라이싱\n', titanic_df[0:2])

In [ ]:
titanic_df[(titanic_df['Sex']=='female') & (titanic_df['Age'] > 40)].head()

In [ ]:
titanic_df.head(3)

In [ ]:
titanic_df.iloc[0, 0]

In [ ]:
titanic_df.iloc[0, 'PassnegerId']

In [ ]:
df = titanic_df['Pclass'].value_counts()

In [ ]:
df

In [ ]:
df.index

In [ ]:
type(df)

In [ ]:
type(df.iloc[0])

In [ ]:
df_reset = df.reset_index(inplace=False)

In [ ]:
df_reset

In [ ]:
type(df_reset.iloc[:2,:1])

In [ ]:
type(titanic_df.loc[0, 'Pclass'])

In [ ]:
type(titanic_df.loc[:5, ['Pclass', 'Age']])

In [ ]:
type(titanic_df.loc[:5, 'Pclass'])

In [ ]:
type(titanic_df)

In [ ]:
titanic_df.iloc[:5, 0]

In [ ]:
df

In [ ]:
df.loc[3:1]

In [ ]:
titanic_bool = titanic_df[titanic_df.Age > 60]
print(type(titanic_bool))
titanic_bool.head(3)

In [ ]:
type(titanic_df[titanic_df['Age'] > 60][['Sex', 'Survived']])

In [ ]:
print(type(titanic_df[titanic_df['Age'] > 60][['Sex']]))
print(type(titanic_df[titanic_df['Age'] > 60]['Sex']))

In [ ]:
titanic_df.loc[titanic_df['Age']>60, ['Survived', 'Sex']].head(3)

In [ ]:
type(titanic_df.loc[titanic_df['Age']>60, ['Survived']])

In [ ]:
type(titanic_df.loc[titanic_df['Age']>60, 'Survived'])

In [ ]:
titanic_df[(titanic_df.Survived == 1) & (titanic_df.Sex == 'male') & (titanic_df.Age > 60)]

In [ ]:
cond1 = titanic_df.Survived == 1
cond2 = titanic_df.Sex == 'male'
cond3 = titanic_df.Age > 60
titanic_df[cond1 & cond2 & cond3]

In [ ]:
titanic_sort = titanic_df.sort_values(by=['Name'])
titanic_sort.head()

In [ ]:
titanic_sort = titanic_df.sort_values(by=['Pclass', 'Name'])
titanic_sort.head()

In [ ]:
titanic_sort = titanic_df.sort_values(by=['Name' , 'Pclass'])
titanic_sort.head()

In [ ]:
titanic_df.count()

In [ ]:
titanic_df.sum()

In [ ]:
titanic_df.Survived.sum()

In [ ]:
titanic_df[['Age', 'Fare']].mean()

In [ ]:
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))
print(titanic_groupby)

In [ ]:
titanic_groupby = titanic_df.groupby('Pclass')
print(type(titanic_groupby))
print(titanic_groupby)

In [ ]:
titanic_groupby.count()

In [ ]:
titanic_groupby = titanic_df.groupby('Pclass').count()
print(type(titanic_groupby))
titanic_groupby

In [ ]:
titanic_groupby = titanic_df.groupby('Pclass', as_index=False).count()
print(type(titanic_groupby))
titanic_groupby

In [ ]:
titanic_df.groupby('Pclass', as_index=False)[['Name', 'Age']].count()

In [ ]:
titanic_df.groupby(['Pclass', 'Sex'], as_index=False)[['Name', 'Age']].count()

In [ ]:
titanic_df.groupby(['Sex', 'Pclass'], as_index=False)[['Name', 'Age']].count()

In [ ]:
titanic_df.groupby(['Sex', 'Survived'], as_index=False)[['Age', 'Fare']].agg(['max', 'mean'])

In [ ]:
agg_form = {'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass', as_index=False).agg(agg_form)

In [ ]:
titanic_df.isna().head()

In [ ]:
titanic_df.isna().sum()

In [ ]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df['Cabin'].fillna('C000', inplace=True)

In [ ]:
titanic_df.head()

In [ ]:
titanic_df['Age'].fillna(titanic_df['Age'].mean(), inplace=True)
titanic_df['Embarked'].fillna('S', inplace=True)
titanic_df.isna().sum()

In [ ]:
def ft_square(n):
    return n**2

print(ft_square(3))

In [ ]:
lambda_square = lambda x: x**2
print(lambda_square(3))

In [ ]:
a = [1,2,3]
square = map(lambda x : x**2, a)
print(type(square))
list(square)

In [ ]:
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x: len(x))
titanic_df[['Name', 'Name_len']].head()

In [ ]:
titanic_df.drop('x', axis=1, inplace=True)

In [ ]:
titanic_df

In [ ]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x: 'Child' if x <= 15 else 'Adult')
titanic_df[['Age', 'Child_Adult']].head()

In [ ]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x: 'Child' if x <= 15 else ('Adult' if x <= 60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

In [ ]:
def get_category(age):
    cat = ''
    if age <= 5: cat = 'Baby'
    elif age <= 12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age <= 25: cat = 'Student'
    elif age <= 35: cat = 'Young Adult'
    elif age <= 60: cat = 'Adult'
    else: cat = 'Elderly'
    
    return cat

In [ ]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x: get_category(x))
titanic_df[['Age', 'Age_cat']].head()

In [55]:
titanic_df['Pclass'].mode()[1]

KeyError: 1